/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary': '#ffffff',
        'surface-container-low': '#fff2e2',
        'surface-bright': '#fff8f3',
        'primary-fixed-dim': '#ffb59f',
        'on-tertiary-container': '#4f2000',
        'on-surface-variant': '#3c4948',
        'secondary': '#006a67',
        'primary-fixed': '#ffdbd1',
        'on-secondary-container': '#00716d',
        'error-container': '#ffdad6',
        'primary-container': '#ff602e',
        'on-secondary-fixed': '#00201f',
        'error': '#ba1a1a',
        'primary': '#af3000',
        'surface': '#fff8f3',
        'on-surface': '#271902',
        'on-primary-container': '#5a1400',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#7bf6f0',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#5bd9d3',
        'inverse-primary': '#ffb59f',
        'inverse-surface': '#3e2e12',
        'surface-container-high': '#ffe4bf',
        'tertiary': '#904c21',
        'on-primary-fixed': '#3a0a00',
        'background': '#fff8f3',
        'surface-container-highest': '#fadfb7',
        'surface-tint': '#af3000',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#00504d',
        'on-tertiary-fixed': '#331200',
        'on-primary-fixed-variant': '#862300',
        'on-tertiary-fixed-variant': '#73350b',
        'outline': '#6c7a78',
        'tertiary-container': '#d28151',
        'secondary-container': '#7bf6f0',
        'inverse-on-surface': '#ffeed9',
        'surface-dim': '#f1d6af',
        'surface-container': '#ffebd1',
        'outline-variant': '#bcc9c8',
        'tertiary-fixed-dim': '#ffb68e',
        'surface-variant': '#fadfb7',
        'on-background': '#271902',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#ffdbca',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
        label: ['"Inter"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
